### ISSUE TITLE
Running colab as is raises exception

### ISSUE THREAD

**Issue by samacqua** [yael-vinker/CLIPasso#9]
Running the base settings on the colab causes the following exception: `torch.nn.modules.module.ModuleAttributeError: 'ModifiedResNet' object has no attribute 'relu'`. This can be solved by replacing m.relu with nn.ReLU(inplace=True), but the resulting images are much lower quality than the ones published in the paper.

<img width="916" alt="Screen Shot 2022-05-03 at 10 04 27 PM" src="https://user-images.githubusercontent.com/11968486/166625492-ea813d97-d99b-42a8-8c83-3bf7a349ba4a.png">
.

**Comment by yael-vinker** [comment]
Hello (: 
This error happens because CLIP source code has been modified in the latest push:
https://github.com/openai/CLIP/commit/b46f5ac7587d2e1862f8b7b1573179d80dcdd620 

I am working on a way to solve this, will keep you posted.
In the meantime, the docker version is more stable and should work properly.
I am also working on a replicate demo to replace the colab one since it has many stability issues with different versions and updates of auxiliary libraries.

**Comment by yael-vinker** [comment]
This should work now on colab as well. I am closing the issue, let me know if you still have any issues :)
